### PR TITLE
More Evil Stuff(Testing)

### PR DESCRIPTION
**Pull request by musabkilic**

### CODE REVIEW

**Comment by musabkilic** [comment]
Cool!

**Comment by shiffman** [comment]
Thanks for doing these experiments! I think for the purpose of learning I'll leave the "evil stuff" out of merging?

**Comment by Rozkalns** [comment]
By adding code coverage threshold that won't go past the CI ;)

**Comment by musabkilic** [comment]
I think it does, but I'm not sure

**Pull request closed without merging**
